//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebelDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public string Marking { get; set; }
        public string Type_Equipment { get; set; }
        public string Specifications { get; set; }
    
        public virtual Type_Equipment Type_Equipment1 { get; set; }
    }
}
