//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebelDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.Specification_furniture = new HashSet<Specification_furniture>();
        }
    
        public string Vendor_code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit_measuring { get; set; }
        public string Type_component { get; set; }
        public Nullable<int> Purchase_price { get; set; }
        public string Main_supplier { get; set; }
        public byte[] Image { get; set; }
        public string Weight { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specification_furniture> Specification_furniture { get; set; }
    }
}
