//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebelDB.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MebelEntities : DbContext
    {
        public MebelEntities()
            : base("name=MebelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assembly_unit_specification> Assembly_unit_specification { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Furniture> Furniture { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Operation_Specification> Operation_Specification { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Specification_furniture> Specification_furniture { get; set; }
        public virtual DbSet<Specification_materials> Specification_materials { get; set; }
        public virtual DbSet<Specifications_EAV> Specifications_EAV { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Equipment> Type_Equipment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Values_EAV> Values_EAV { get; set; }
    }
}
