//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebelDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Specification
    {
        public string Product { get; set; }
        public string Operation { get; set; }
        public int Serial_Number { get; set; }
        public string Type_Equipment { get; set; }
        public Nullable<System.TimeSpan> Time_on_operation { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Type_Equipment Type_Equipment1 { get; set; }
    }
}
