//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebelDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id_Order { get; set; }
        public System.DateTime Data { get; set; }
        public string Name_Order { get; set; }
        public string Product { get; set; }
        public string Customer { get; set; }
        public string Responsible_Manager { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<System.DateTime> Planned_date_Completion { get; set; }
        public byte[] Schemes_drawings_Order { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
